# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from ssigmaapi.productibit.v1 import productibit_pb2 as ssigmaapi_dot_productibit_dot_v1_dot_productibit__pb2


class ProductibitServiceV1Stub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.UploadSensor = channel.unary_unary(
        '/ssigmaapi.productibit.v1.ProductibitServiceV1/UploadSensor',
        request_serializer=ssigmaapi_dot_productibit_dot_v1_dot_productibit__pb2.SensorMessage.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class ProductibitServiceV1Servicer(object):
  # missing associated documentation comment in .proto file
  pass

  def UploadSensor(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProductibitServiceV1Servicer_to_server(servicer, server):
  rpc_method_handlers = {
      'UploadSensor': grpc.unary_unary_rpc_method_handler(
          servicer.UploadSensor,
          request_deserializer=ssigmaapi_dot_productibit_dot_v1_dot_productibit__pb2.SensorMessage.FromString,
          response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'ssigmaapi.productibit.v1.ProductibitServiceV1', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
